---
- name: Install vim and neovim
  apt:
      pkg:
          - neovim
          - vim

- name: Create init.vim directory
  file:
      path: "{{ base }}/.config/nvim"
      state: directory
      owner: "{{ user }}"
      group: "{{ group }}"

- name: Create init.vim
  template:
      src: nvim.config
      dest: "{{ base }}/.config/nvim/init.vim"
      owner: "{{ user }}"
      group: "{{ group }}"

- name: Clone configs repository
  git:
      repo: 'https://github.com/pCosta99/configs.git'
      dest: "/tmp/configs"

- name: Copy .vimrc into home folder
  template:
      src: "/tmp/configs/.vimrc"
      dest: "{{ base }}/.vimrc"
      owner: "{{ user }}"
      group: "{{ group }}"

- name: Install Pathogen
  shell: "mkdir -p {{ base }}/.vim/autoload {{ base }}/.vim/bundle && curl -LSso {{ base }}/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim"

- name: Install Vundle
  git:
      repo: 'https://github.com/VundleVim/Vundle.vim.git'
      dest: "{{ base }}/.vim/bundle/Vundle.vim"

- name: Install Plug
  shell: "curl -fLo {{ base }}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

- name: Fix permissions
  file:
      dest: "{{ base }}/.vim"
      owner: "{{ user }}"
      group: "{{ group }}"
      recurse: yes
